spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://192.168.142.132:8084
  zipkin:
    base-url: http://192.168.142.132:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.142.136:26379, 192.168.142.136:26380, 192.168.142.136:26381

server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.142.132:8761/eureka/,http://192.168.142.132:8861/eureka/,http://192.168.142.132:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info