version: '3.1'
services:
  itoken-admin:
    restart: always
    image: 192.168.142.134:5000/itoken-admin
    container_name: itoken_admin
    ports:
      - 8084:8084
    networks:
      - admin_network

networks:
  admin_network: