version: '3.1'
services:
  itoken-config:
    restart: always
    image: 192.168.142.134:5000/itoken-config
    container_name: itoken_config
    ports:
      - 8888:8888
    networks:
      - config_network

networks:
  config_network: