version: '3.1'
services:
  itoken-zuul:
    restart: always
    image: 192.168.142.134:5000/itoken-zuul
    container_name: itoken_zuul
    ports:
      - 8769:8769
    networks:
      - zuul_network

networks:
  zuul_network: